spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_marcao?useTimeZone=true&serverTimeZone=UTC
    username: root
    password: Teste123@
    driver-class-name: com.mysql.cj.jdbc.Driver
    # Optional DBCP2 configuration
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      max-wait-millis: 10000
      validation-query: SELECT 1
      log-abandoned: true
      default-auto-commit: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false

    application:
      name=api-dummy: